---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-fargate
  template:
    metadata:
      labels:
        app: demo-fargate
    spec:
      containers:
        - name: demo-frontend
          image: 596152156334.dkr.ecr.sap-northeast-2.amazonaws.com/demo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
